// Generated by CoffeeScript 1.4.0
var _;

_ = {};

_.extend = function() {
  var a, b, i, k;
  a = arguments;
  i = a.length;
  while (i-- > 1) {
    b = a[i];
    for (k in b) {
      a[0][k] = b[k];
    }
  }
  return a[0];
};
