// Generated by CoffeeScript 1.4.0

$.create = function(html) {
  return ($.createElement('div').innerHTML = html).childNodes;
};

Element.prototype.append = $.appendChild;

Element.prototype.appendTo = function(o) {
  o.append(this);
};

Element.prototype.empty = function() {
  while (this.hasChildNodes()) {
    this.removeChild(this.lastChild);
  }
};
