// Generated by CoffeeScript 1.4.0
var $;

$ = document;

$.liveId = $.getElementById;

$.liveTag = $.getElementsByTagName;

$.liveClass = $.getElementsByClassName;

$.one = $.querySelector;

$.all = $.querySelectorAll;

Element.prototype.one = Element.prototype.querySelector;

Element.prototype.all = Element.prototype.querySelectorAll;
