// Generated by CoffeeScript 1.4.0
var $;

$ = document;

$.liveId = $.getElementById;

$.liveTag = $.getElementsByTagName;

$.liveClass = $.getElementsByClassName;

$.one = $.querySelector;

$.all = $.querySelectorAll;

Element.prototype.one = Element.prototype.querySelector;

Element.prototype.all = Element.prototype.querySelectorAll;

$.create = function(html_src) {
  return new DOMParser().parseFromString(html_src, 'text/xml').childNodes[0];
};

Element.prototype.append = $.appendChild;

Element.prototype.appendTo = function(o) {
  return o.append(this);
};

Element.prototype.empty = function() {
  var _results;
  _results = [];
  while (this.hasChildNodes()) {
    _results.push(this.removeChild(this.lastChild));
  }
  return _results;
};

$.xhr = function(method, url, data, cb) {
  var r;
  try {
    r = new XMLHttpRequest();
    r.open(method, url, true);
    r.onreadystatechange = function() {
      if (r.readyState !== 4) {
        return;
      }
      if (r.status !== 200) {
        return cb(r.statusText, null, r.status, r);
      }
      return cb(null, r.responseText, r.status, r);
    };
    r.send(data || undefined);
  } catch (err) {
    return cb(err, null, r.status, r);
  }
};
